#!/bin/bash
echo "QTC Blockchain Project Structure:"
echo ""
tree -I 'build|*.o|*.exe' || {
    echo "qtc-blockchain/"
    echo "├── src/"
    echo "│   ├── main_full.cpp"
    echo "│   ├── network/"
    echo "│   │   └── P2PNode.cpp"
    echo "│   ├── crypto/"
    echo "│   │   └── ZKProof.cpp"
    echo "│   ├── rpc/"
    echo "│   │   └── RPCServer.cpp"
    echo "│   └── contracts/"
    echo "│       └── VirtualMachine.cpp"
    echo "├── include/"
    echo "│   ├── network/"
    echo "│   │   └── P2PNode.h"
    echo "│   ├── crypto/"
    echo "│   │   └── ZKProof.h"
    echo "│   ├── rpc/"
    echo "│   │   └── RPCServer.h"
    echo "│   └── contracts/"
    echo "│       └── VirtualMachine.h"
    echo "├── web/"
    echo "│   ├── index.html"
    echo "│   ├── app.js"
    echo "│   └── style.css"
    echo "├── CMakeLists.txt"
    echo "└── README.md"
}
